// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZLlicYkAxwlI1CHnxiczpO68CR-pTTW0',
    appId: '1:858204646609:web:114921b5d6baf23886e9f0',
    messagingSenderId: '858204646609',
    projectId: 'rapido-af332',
    authDomain: 'rapido-af332.firebaseapp.com',
    storageBucket: 'rapido-af332.firebasestorage.app',
    measurementId: 'G-PRHVY7VFQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD75B1BSKCXeNgfZ9cah4Z25ChVF9-oyHg',
    appId: '1:858204646609:android:4a3bf86d603eeff386e9f0',
    messagingSenderId: '858204646609',
    projectId: 'rapido-af332',
    storageBucket: 'rapido-af332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3w8XEip_G8BWNxpJeI0uPGjMsC_Vpquc',
    appId: '1:858204646609:ios:481d1b8b6539c83086e9f0',
    messagingSenderId: '858204646609',
    projectId: 'rapido-af332',
    storageBucket: 'rapido-af332.firebasestorage.app',
    iosBundleId: 'com.example.rapido',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3w8XEip_G8BWNxpJeI0uPGjMsC_Vpquc',
    appId: '1:858204646609:ios:481d1b8b6539c83086e9f0',
    messagingSenderId: '858204646609',
    projectId: 'rapido-af332',
    storageBucket: 'rapido-af332.firebasestorage.app',
    iosBundleId: 'com.example.rapido',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZLlicYkAxwlI1CHnxiczpO68CR-pTTW0',
    appId: '1:858204646609:web:ca5f1f9ae583acb686e9f0',
    messagingSenderId: '858204646609',
    projectId: 'rapido-af332',
    authDomain: 'rapido-af332.firebaseapp.com',
    storageBucket: 'rapido-af332.firebasestorage.app',
    measurementId: 'G-X8GZ8QV4PR',
  );
}
